### ISSUE TITLE
Customise the camera UI

### ISSUE THREAD

**Issue by menjada** [NeutrinosPlatform/cordova-plugin-document-scanner#27]
Hi is it possible to send some options when the scan object triggers the camera.
For example:
- Change color on the "scan detection" with is red now.
- Make "color" image  as default.

**Comment by ChrisTomAlx** [comment]
Hey menjada,

You mean for iOS right? Presently this is not possible, since it will require changes in the library that is used for scanning. But I will add it to our future enhancement list. Thank you raising an issue.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
