### ISSUE TITLE
App Crushes in android 8.1 

### ISSUE THREAD

**Issue by basilhskk** [NeutrinosPlatform/cordova-plugin-document-scanner#38]
Ionic app crushes as soon as plugin scan starts . Android version 8.1.0. Please help !

**Comment by ChrisTomAlx** [comment]
Fixed and tested! Let me know if you are facing more issues.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by ravi9376** [comment]
still i m facing same problem when select option app directly close.

**Comment by ravi9376** [comment]
some time when i select image from camera and after that select image from gallery then also app crush and showing me to restart app

**Comment by ChrisTomAlx** [comment]
@ravi9376 

It is better if you open a new issue because this is likely caused due to something else. In the new issue that you open please give a detailed description of your problem. Along with expected behavior / Android version details / cordova version details / stack trace / Your usage of the plugin / anything else you think will help me solve your problem.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
